# Generated by Django 5.1.2 on 2025-07-08 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='expected_yield_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_date',
            field=models.DateField(),
        ),
    ]
