# Generated by Django 5.1.2 on 2025-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_forecast_created_at_alter_forecast_expected_yield_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='area_ha',
            field=models.FloatField(default=1.0, help_text='Area in hectares'),
        ),
        migrations.AddField(
            model_name='activity',
            name='fert_sacks',
            field=models.FloatField(blank=True, help_text='Total # of 50kg fertilizer sacks applied (baseline plan)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='seed_qty_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='spacing',
            field=models.CharField(blank=True, help_text="e.g. '20x20 cm' or '10x10 m'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_harvest_max',
            field=models.PositiveIntegerField(default=130),
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_harvest_min',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='fert_sacks_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='fert_sacks_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_rate_max_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_rate_min_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='yield_t_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='yield_t_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='harvest_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='harvest_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='input_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='population_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='season_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='yield_max_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='forecast',
            name='yield_min_kg',
            field=models.FloatField(default=0),
        ),
    ]
