# Generated by Django 5.1.2 on 2026-02-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_delete_faq_delete_supportcontact_expense_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('labor', 'Labor'), ('pesticide', 'Pesticide'), ('fuel', 'Fuel'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='month',
            field=models.CharField(max_length=100),
        ),
    ]
