# Generated by Django 5.1.2 on 2026-03-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_expense_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Select the admin who will manage this farmer', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farmers', to=settings.AUTH_USER_MODEL),
        ),
    ]
